{% set name = "pygaps" %}
{% set version = "4.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  skip: true  # [py<37]
  entry_points:
    - pygaps = pygaps.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygaps-{{ version }}.tar.gz
  sha256: 5bdf02b497a955b19114bff9e42bce39fb133324da10a2d1c3e978b2ad452fc4

requirements:
  host:
    - pip
    - python
  run:
    - coolprop >=6.0
    - gemmi
    - importlib-resources  # [py<39]
    - matplotlib-base
    - numpy >=1.16.5
    - openpyxl
    - pandas
    - python
    - requests
    - scipy >=1.6
    - xlrd >=1.1
    - xlwt >=1.3

test:
  imports:
    - pygaps
  commands:
    - pip check
    - pygaps --help
  requires:
    - pip

about:
  home: https://github.com/pauliacomi/pygaps
  summary: A framework for processing adsorption data for porous materials.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pauliacomi
